---
# handlers file for eea
- name: reboot hosts
  command: /sbin/shutdown -r now
  async: 0
  poll: 0
  ignore_errors: true
  #listen: "reboot server"

- name: wait for vm up
  wait_for:
    host: "{{ inventory_hostname }}"
    port: 22
    search_regex: OpenSSH
    state: started
    delay: 10
  #listen: "reboot server"
  connection: local

- name: restart ntp service
  service: name=ntp state=restarted

