- hosts: nfs-client
  remote_user: ubuntu
  become: true
  become_method: sudo
  become_user: root
  #vars:
    #master1: "roy1.localnova"

  tasks:
    - name: Create share dir
      file: path=/data/eea state=directory
    
#    - name: remove lock file
#      file:
#        path: "{{ item }}"
#        state: absent
#      with_items:
#        - /var/lib/dpkg/lock
#        - /var/cache/apt/archives/lock
#    
#    - name: apt install nfs-client
#      apt: name=nfs-common state=present
    
    - name: mount the dir
      mount:
        name: /data/eea
        src: "{{ groups['nfs-server'][0] }}:/data/eea"
        #src: "{{ master1 }}:/data/eea"
        fstype: nfs
        state: mounted
      #mount: name=/data/eea src="{{ groups['nfs-server'] }}:/data/eea" fstype=nfs state=mounted
      #mount: name=/data/eea src="{{ groups['nfs-server'] }}:/data/eea" fstype=nfs state=mounted
