---
- import_playbook: eea-all.yml
- import_playbook: eea-master.yml
- import_playbook: ambari-agent.yml
- import_playbook: nfs-client.yml
- import_playbook: postgres.yml
- import_playbook: redis.yml
- import_playbook: blueprint.yml
