#!/bin/bash
# Check for specific interface if desired
[ "$IFACE" != "eth0" ] || exit 0
# Adding additional routes on connection
#route add -net 31.135.208.0/21 gw 192.168.2.1 dev eth0
# All VMs in traffic-subnet  go outside via gateway 192.168.34.125
# All VMs in data-subnet  go outside via gateway 192.168.34.189
route add default gw 192.168.34.125 dev eth0
route del default gw 192.168.34.1
