---
- name: install psycopg2 package for postgres module
  pip: name=psycopg2

- name: create postgres hive and oozie db
  postgresql_db:
    name: "{{ item }}"
  with_items:
    - hive
    - oozie
  become_user: postgres

- name: Create user and grant access to database
  postgresql_user:
    db: "{{ item.db }}"
    name: "{{ item.user }}"
    password: "{{ item.pass }}"
    priv: "ALL"
  with_items:
    - { 'db': 'hive', 'user': 'hive', 'pass': 'hive' }
    - { 'db': 'oozie', 'user': 'oozie', 'pass': 'oozie' }
  become_user: postgres

- name: change postgre pg_hba.conf
  template: src=pg_hba.conf.j2 dest=/var/lib/pgsql/data/pg_hba.conf backup=yes
  tags: pg_hba

- name: copy postgresql.conf
  lineinfile:
    dest: /var/lib/pgsql/data/postgresql.conf
    regexp: "^#?listen_addresses"
    line: "listen_addresses = '*'"
    state: present
    backrefs: yes
    backup: yes
  tags: listen_port
  notify:
   - restart postgresql service

- meta: flush_handlers
  
