---
# tasks file for ambari-agent
- name: copy ambari yum repo file
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { 'src': 'ambari.repo.j2', 'dest': '/etc/yum.repos.d/ambari.repo' }
#    - { 'src': 'ambari-hdp-1.repo.j2', 'dest': '/etc/yum.repos.d/ambari-hdp-1.repo' }
  tags: copy_yum_repo_conf

- name: copy priorities.conf file
  copy:
    src: priorities.conf
    dest: /etc/yum/pluginconf.d/priorities.conf

- name: yum Install ambari-agent package
  yum:
    #update_cache: yes
    name: ambari-agent
    state: present

- name: Configure the Ambari agent
  lineinfile:
     dest: /etc/ambari-agent/conf/ambari-agent.ini
     regexp: '^hostname\s*='
     line: "hostname={{ hostvars[groups['eea-all'][0]]['inventory_hostname'] }}"
     state: present
     backrefs: yes
  notify: Restart ambari-agent

- meta: flush_handlers

- name: Make sure ambari-agent is running
  service: name=ambari-agent state=started enabled=yes

- import_tasks: jdbc_download.yml
  tags: jdbc

- import_tasks: bug_fix.yml
  tags: bug_fix

#- name: Configure the Ambari agent - disable proxy
#  lineinfile: dest=/etc/yum.conf
#              regexp='^proxy=http://10.175.250.81:8080'
#              line='#proxy=http://10.175.250.81:8080'
#              state=present
#              backrefs=yes
#  tags: disable_yum_proxy
