---
- name: unarchive 3pp packages
  unarchive:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    remote_src: yes
  with_items:
    - { 'src': 'http://192.168.34.77/3pp/dist-packages_MS2_user.tar.gz', 'dest': '/usr/local/lib/python2.7' }
    - { 'src': 'http://192.168.34.77/3pp/dist-packages_MS2_os.tar.gz', 'dest': '/usr/lib/python2.7' }

- name: pip install json-tools
  pip: name=json-tools
  environment:
    https_proxy: "{{ HTTP_PROXY }}"

#- name: copy pip-txt file
#  copy: src=pip_req.txt dest=/tmp/pip_req.txt
#
#- name: pip install
#  pip: requirements=/tmp/pip_req.txt
#  environment:
#    http_proxy: "{{ HTTP_PROXY }}"
#    https_proxy: "{{ HTTP_PROXY }}"

