---
- name: proxy setting via global initialization scripts for each user
  template: src=proxy.sh.j2 dest=/etc/profile.d/proxy.sh mode=644
  tags: proxy_setting

- name: yum proxy setting
  lineinfile:
      dest: /etc/yum.conf
      state: present
      backrefs: yes
      line: 'proxy={{ HTTP_PROXY }}'

- name: update /etc/hosts file with other servers
  template: src=hosts.j2 dest=/etc/hosts
  tags: hostfile
 
#- name: update hostname file
#  shell: echo "{{ hostname }}"> /etc/hostname
#
#- name: check hostname
#  command: cat /etc/hostname
#  register: hn
#
#- debug: var=hn.stdout

#- name: set hostname
#  shell: 'hostnamectl --static set-hostname {{ hostname }}'
#  tags: hostname

#- name: set hostname
#  hostname:
#    name: "{{ hostname }}"
#  tags: hostname


