---
#- name: remove lock file
#  file:
#    path: "{{ item }}"
#    state: absent
#  with_items:
#    - /var/lib/dpkg/lock
#    - /var/cache/apt/archives/lock

- name: apt install pip
  apt: 
    name: "{{ item }}"
    state: present
  with_items:
#    - python-psycopg2
    - python-pip

- name: upgrade pip
  pip:
    name: pip
    state: latest
  environment:
    https_proxy: "{{ HTTP_PROXY }}"
  tags: upgrade-pip
