---
- name: EPEL via yum
  yum: name=epel-release state=present

- name: yum install pip
  yum: 
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - python2-pip
    - python-devel
#  notify: upgrade pip

- name: upgrade pip
  pip:
    name: pip
    state: latest
  environment:
    https_proxy: "{{ HTTP_PROXY }}"
  tags: upgrade-pip

#- meta: flush_handlers

#- name: unarchive 3pp packages
#  unarchive:
#    src: "{{ item.src }}" 
#    dest: "{{ item.dest }}"
#  with_items:
#    - { 'src': 'dist-packages_MS2_user.tar.gz', 'dest': '/usr/local/lib/python2.7' } 
#    - { 'src': 'dist-packages_MS2_os.tar.gz', 'dest': '/usr/lib/python2.7' } 
#  tags: 3pp
#
#- name: pip install json-tools
#  pip: name=json-tools
#  environment:
#    https_proxy: "{{ HTTP_PROXY }}"

- name: copy pip-txt file
  copy: src=pip_req.txt dest=/tmp/pip_req.txt

- name: pip install 3pp
  pip: requirements=/tmp/pip_req.txt 
  environment:
    http_proxy: "{{ HTTP_PROXY }}"
    https_proxy: "{{ HTTP_PROXY }}"
