---
- name: EPEL via yum
  #yum: name=epel-release state=present
  yum:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    state: present

- name: yum install pip
  yum: 
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - python2-pip
    - python-devel

- name: upgrade pip
  pip:
    name: pip
    state: latest
  tags: upgrade-pip

#- name: copy pip-txt file
#  copy: src=pip_req.txt dest=/tmp/pip_req.txt
#
#- name: pip install 3pp
#  pip: requirements=/tmp/pip_req.txt 
#  environment:
#    https_proxy: "{{ HTTP_PROXY }}"
