---
- name: generate ssh key for root
  user: 
    name=root
    generate_ssh_key=yes

- name: Get public keys for master
  shell: cat /root/.ssh/id_rsa.pub
  register: master_ssh_key

- name: create public_keys directory if it does not existing.
  file: 
    path: /tmp/public_keys
    state: directory
  connection: local

- name: Delete pub files if existing
  local_action:
    module: file
    path: "{{ item }}"
    state: absent
  with_fileglob:
    - /tmp/public_keys/*.pub

- name: Copy ssh key into file
  local_action: copy content={{ master_ssh_key.stdout }} dest=/tmp/public_keys/{{ inventory_hostname }}.pub 

- name: Add public keys for developers
  authorized_key: user=root key={{ lookup('file', item) }}
  with_fileglob:
   - /tmp/public_keys/*.pub
