---

- name: remove lock file
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /var/lib/dpkg/lock
    - /var/cache/apt/archives/lock

- name: apt install traceroute
  apt: name=traceroute state=present update_cache=yes cache_valid_time=3600

#- name: install ntp package
#  command: apt install ntp -y
#  apt: name=ntp state=present force=yes
  #with_items:
  #  - ntpdate 
  #  - ntp
  #environment: "{{ proxy_env }}"   
    #http_proxy: "{{ HTTP_PROXY }}"

#- name: set timezone
#  command: timedatectl set-timezone Asia/Shanghai
