---
- name: copy environment for system level proxy setting
  copy: src=environment dest=/etc/environment mode=644
    
- name: copy apt.conf for apt-get  proxy setting
  copy: src=apt.conf.proxy dest=/etc/apt/apt.conf
    
#- name: update routing table for default gw
#  command: "{{ item }}"
#  with_items:
#    - "route add default gw 192.168.34.125"
#    - "route del default gw 192.168.34.1"

#- name: update DNS client setting
  #copy: src=resolv.conf dest=/etc/resolv.conf

#- name: set hostname
  #hostname: name=EEA1.localnova

- name: update /etc/hosts file with other servers
  copy: src=hosts dest=/etc/hosts
#- name: update /etc/hosts file with other servers
  #blockinfile:
    #path: /etc/hosts
    #block: |
      #192.168.34.83  EEA1.localnova 
      #192.168.34.84 EEA2.localnova
      #192.168.34.85 EEA3.localnova
