---
- name: Create share dir
  file: path=/data/eea state=directory

- name: apt install nfs-client
  apt: name=nfs-common state=present

#- name: update fstab file for nfs client
 # lineinfile: dest=/etc/fstab regexp='sh-rms-eea-upgrade-1.localnova:/data/eea /data/eea nfs defaults 0 0' state=absent

- name: mount the dir
  mount: 
    name: /data/eea
    src: sh-rms-eea-upgrade-1.localnova:/data/eea
    fstype: nfs
    state: mounted
