---
#- name: remove lock file
#  file:
#    path: "{{ item }}"
#    state: absent
#  with_items:
#    - /var/lib/dpkg/lock
#    - /var/cache/apt/archives/lock

- name: apt install pip
  apt: 
    name: "{{ item }}"
    state: present
  with_items:
    - python-psycopg2
    - python-pip

- name: unarchive 3pp packages
  unarchive:
    src=dist-packages.tar.gz dest=/usr/local/lib/python2.7

#- name: copy pip-txt file
#  copy: src=pip_req.txt dest=/tmp/pip_req.txt
#
#- name: pip install
#  pip: requirements=/tmp/pip_req.txt 
#  environment:
#    http_proxy: http://10.24.16.228:3128
#    https_proxy: http://10.24.16.228:3128
