---
# handlers file for ambari-server
- name: Restart ambari-server
  service: name=ambari-server state=restarted


- name: ambari-server setup via expect
  expect:
    command: /usr/sbin/ambari-server setup
    responses:
      'Customize user account for ambari-server daemon \[y/n\] \(n\)\?': 'n'
      'Enter choice \(1\):': '3'
      'Path to JAVA_HOME:': '/usr/java/jdk1.8.0_162'
      'Enable Ambari Server to download and install GPL Licensed LZO packages \[y/n\] \(n\)\?': 'n'
      'Enter advanced database configuration \[y/n\] \(n\)\?': 'n'

    echo: yes
    timeout: 60
#  environment:
#    http_proxy: "{{ HTTP_PROXY }}"
  register: ambari_server_setup
  listen: ambari-server-setup

- debug: var=ambari_server_setup
  listen: ambari-server-setup

- name: restart postgresql service
  service: name=postgresql state=restarted
