---
# tasks file for postgres
- name: install repository rpm
  yum:
    name: https://download.postgresql.org/pub/repos/yum/9.4/redhat/rhel-7-x86_64/pgdg-centos94-9.4-2.noarch.rpm
  environment:
    https_proxy: "{{ HTTP_PROXY }}"

- name: yum install postgres-9.4
  yum: name='postgresql94-server' state='present'
  notify:
   - init db

- meta: flush_handlers

- name: change postgre pg_hba.conf
  template: src=pg_hba.conf.j2 dest=/var/lib/pgsql/9.4/data/pg_hba.conf backup=yes
  tags: pg_hba

- name: copy postgresql.conf
  lineinfile:
    dest: /var/lib/pgsql/9.4/data/postgresql.conf
    regexp: "^#?listen_addresses"
    line: "listen_addresses = '*'"
    state: present
    backup: yes
  tags: listen_port
  notify:
   #- init db
   - restart postgresql service

- meta: flush_handlers

- name: install python psycopg2 module
  pip: name=psycopg2
  environment:
    https_proxy: "{{ HTTP_PROXY }}"

- name: set password for postgres
  postgresql_user:
    db: postgres
    user: postgres
    password: postgres
 

